name: Netlify Builds

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        name: "Checkout Source Code"

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 18.x

      - name: Build the site
        run: |
          yarn install --production
          yarn build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1.3
        with:
          publish-dir: './public'
          production-branch: master
          deploy-message: '${{ github.event.head_commit.message }}'
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
